# VisionProcessor configuration

# Camera ID handled by this VisionProcessor instance.
#cam_id: 0

# Total camera amount over the field
#camera_amount: 1

# Camera source type. Availability depending on libraries installed.
# SPINNAKER, IMAGES, OPENCV
source: SPINNAKER

# Spinnaker camera id
#spinnaker_id: 0

#OpenCV camera device or video file path
#opencv_path: /dev/video0

# List of image file system paths for IMAGES source.
#images: []

# Team bot heights yml file (heights in mm)
#bot_heights_file: robot-heights.yml

# Side blob distance in mm
#side_blob_distance: 65.0

# Center blob radius in mm
#center_blob_radius: 25.0

# Side blob radius in mm
#side_blob_radius: 20.0

# Ball radius in mm
#ball_radius: 21.5

thresholds:
  # Minimum mean cosine similarity of the blob border gradient (0 - 1)
  #circularity: 50.0
  # Minimum saturation of the blob area (0 - 255)
  #saturation: 24
  # Minimum brightness of the blob area (0 - 255
  #brightness: 32

# Hues of the colors used to classify the blobs in ° (0 - 359°)
hues:
  #orange: 30.0
  #yellow: 60.0
  #blue: 210.0
  #green: 120.0
  #pink: 300.0

tracking:
  # Min tracking radius in mm
  #min_tracking_radius: 30.0

  # Max tracked ball velocity in m/s
  #max_ball_velocity: 8.0

  # Max tracked bot acceleration in m/s^2
  #max_bot_acceleration: 6.5

network:
  # Game controller multicast ip address
  #gc_ip: "224.5.23.1"
  # Game controller multicast port
  #gc_port: 10003

  # Vision multicast IP address
  #vision_ip: "224.5.23.2"
  # Vision multicast port
  #vision_port: 10006

  # Camera stream ip prefix
  #stream_ip_base_prefix: 224.5.23.
  # Camera stream ip end base (cam_id is added to maintain separation)
  #stream_ip_base_end: 100
  # Camera stream port
  #stream_port: 10100
