# VisionProcessor configuration

# Vision camera ID handled by this VisionProcessor instance.
#cam_id: 0

camera:
  # Camera driver type. Availability depending on libraries installed.
  # Existing: SPINNAKER (FLIR cameras), MVIMPACT (Bluefox3 cameras), OPENCV(files, v4l2 cameras)
  #driver: SPINNAKER
  # Spinnaker, mvIMPACT or OpenCV(v4l2) camera id
  #id: 0
  # OpenCV camera device, image or video file path (if not set id is used instead)
  #path: /dev/video0
  # Spinnaker camera exposure time in ms to adjust brightness. Higher values lead to more motion blur.
  # Camera framerate will drop if set equal to or higher than the frametime (1 / fps_cam).
  # 0.0 = automatic exposure
  #exposure: 0.0
  # Spinnaker camera gain to adjust brightness. Higher values lead to more noise.
  # 0.0 = automatic gain
  #gain: 0.0
  # Spinnaker camera white balance. OUTDOOR or INDOOR for auto white balance with green or gray carpet respectively.
  # [Blue white balance, Red white balance] for manual white balance.
  #white_balance: OUTDOOR

geometry:
  # Total camera amount over the field
  #camera_amount: 1
  # Camera height above field in mm
  # 0.0 = automated camera height calibration, this does not work if the camera looks perpendicular to the field
  #camera_height: 0.0
  # Minimum brightness difference to surrounding pixels for the classification as field line pixel (0 - 255)
  #field_line_threshold: 5
  # Minimum length of line segments to ensure angular stability in pixels
  #min_line_segment_length: 10.0
  # Maximum perpendicular offset of line segments for merging in pixels
  #max_line_segment_offset: 10.0
  # Maximum relative angle of line segments for merging in Â°
  #max_line_segment_angle: 3.0
  # Minimum length for classifying field lines as major (fraction of the image size)
  #min_major_line_length: 0.5
  # Maximum field line intersection distance from the visible image plane (fraction of the image size)
  #max_intersection_distance: 0.2

thresholds:
  # Minimum mean cosine similarity (not normalized) of the blob border gradient (0 - 195075.0)
  #circularity: 25.0
  # Minimum circularity/(3*stddev) blob score
  #score: 0.0

  # Max blobs
  #blobs: 2000

  # Minimum distance between two robots in robot radii
  #min_robot_distance: 1.75
  #min_ball_distance: 0.8

sizes:
  # Team bot heights yml file (heights in mm)
  #bot_heights_file: robot-heights.yml
  # Center blob radius in mm
  #center_blob_radius: 25.0
  # Side blob radius in mm
  #side_blob_radius: 20.0

tracking:
  # Min tracking radius in mm
  #min_tracking_radius: 20.0

  # Max tracked ball velocity in m/s
  #max_ball_velocity: 8.0

  # Max tracked bot acceleration in m/s^2
  #max_bot_acceleration: 6.5

network:
  # Game controller multicast ip address
  #gc_ip: "224.5.23.1"
  # Game controller multicast port
  #gc_port: 10003

  # Vision multicast IP address
  #vision_ip: "224.5.23.2"
  # Vision multicast port
  #vision_port: 10006

  # Camera stream ip prefix
  #stream_ip_base_prefix: 224.5.23.
  # Camera stream ip end base (cam_id is added to maintain separation)
  #stream_ip_base_end: 100
  # Camera stream port
  #stream_port: 10100

debug:
  # Ground truth file
  #ground_truth: gt.yml
  # Wait for geometry prior to processing frames
  #wait_for_geometry: false
  # Print code debug images
  #debug_images: false
